"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { PromoPackDisplay } from "@/components/business/promo-pack-display";
import type { BusinessProfile, PromoPack } from "@/lib/business/schemas";

type SavedProfile={id:string;businessName:string|null;websiteUrl:string;industry:string|null;createdAt:string};
const EMPTY: BusinessProfile = {websiteUrl:"",businessName:"",industry:"",targetAudience:"",mainOffer:"",productsOrServices:[],keyBenefits:[],painPointsSolved:[],brandTone:"",contentAngles:[],ctaIdeas:[],oneLineSummary:"",longSummary:""};
export default function Page(){const [websiteUrl,setWebsiteUrl]=useState("");const [profile,setProfile]=useState<BusinessProfile|null>(null);const [promoPack,setPromoPack]=useState<PromoPack|null>(null);const [savedId,setSavedId]=useState<string|null>(null);const [saved,setSaved]=useState<SavedProfile[]>([]);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [gen,setGen]=useState(false);const [error,setError]=useState('');const [ok,setOk]=useState('');
const p=profile??EMPTY;const step=useMemo(()=>!profile?1:!promoPack?2:3,[profile,promoPack]);
useEffect(()=>{fetch('/api/business/profiles').then(r=>r.json()).then(j=>setSaved((j.profiles??[]).slice(0,3))).catch(()=>{})},[]);
const upd=<K extends keyof BusinessProfile>(k:K,v:BusinessProfile[K])=>setProfile(prev=>({...(prev??EMPTY),[k]:v}));
return <div className='mx-auto max-w-6xl space-y-6'>
<section className='cl-card p-6'><span className='inline-flex rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700'>Business Context Engine</span><h1 className='mt-3 text-3xl font-semibold'>Turn your website into a promo content engine.</h1><p className='mt-2 text-slate-600'>Paste your website and ClipLoop will learn your business, extract your offer, and generate ready-to-post short-form promo content.</p></section>
<section className='cl-card p-5'><div className='flex items-center justify-between'><h2 className='text-lg font-semibold'>Saved businesses</h2><Link href='/dashboard/business/profiles' className='text-sm text-emerald-700'>View all saved businesses</Link></div><div className='mt-3 grid gap-3 md:grid-cols-3'>{saved.length===0?<p className='text-sm text-slate-500'>No saved businesses yet.</p>:saved.map(s=><div key={s.id} className='rounded-xl border p-3 text-sm'><p className='font-semibold'>{s.businessName||'Untitled business'}</p><p className='text-slate-500'>{s.websiteUrl}</p><p>{s.industry||'—'}</p><p className='text-xs text-slate-500 mt-1'>{new Date(s.createdAt).toLocaleDateString()}</p><Link href={`/dashboard/business/${s.id}`} className='text-emerald-700 text-xs'>Open</Link></div>)}</div></section>
<section className='grid gap-3 md:grid-cols-3'>{['Analyze website','Review business profile','Generate promo pack'].map((t,i)=><div key={t} className={`rounded-2xl border px-4 py-3 ${step>=i+1?'border-emerald-300 bg-emerald-50':'bg-white'}`}><p className='text-xs'>Step {i+1}</p><p className='font-medium text-sm'>{t}</p></div>)}</section>
<section className='cl-card p-5'><input className='w-full rounded-xl border p-2.5' value={websiteUrl} onChange={e=>setWebsiteUrl(e.target.value)} placeholder='https://yourbusiness.com' /><div className='mt-3'><Button onClick={async()=>{setLoading(true);setError('');setOk('');try{const r=await fetch('/api/business/analyze-website',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({websiteUrl})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Analyze failed');setProfile(j.profile);setOk('Business context extracted.');}catch(e:any){setError(e.message)}finally{setLoading(false);}}} disabled={loading||!websiteUrl}>{loading?'Analyzing...':'Analyze Website'}</Button></div>{loading?<p className='text-sm mt-2 text-slate-600'>Reading your website and building your business context...</p>:null}</section>
{profile?<section className='cl-card p-5 grid gap-3 md:grid-cols-2'>{(['businessName','websiteUrl','industry','targetAudience','mainOffer','brandTone'] as const).map(k=><label key={k}><span className='text-sm'>{k}</span><input className='w-full rounded-xl border p-2 mt-1' value={p[k]} onChange={e=>upd(k,e.target.value)} /></label>)}<label className='md:col-span-2'><span className='text-sm'>oneLineSummary</span><input className='w-full rounded-xl border p-2 mt-1' value={p.oneLineSummary} onChange={e=>upd('oneLineSummary',e.target.value)} /></label><label className='md:col-span-2'><span className='text-sm'>longSummary</span><textarea className='w-full rounded-xl border p-2 mt-1' value={p.longSummary} onChange={e=>upd('longSummary',e.target.value)} /></label>{(['productsOrServices','keyBenefits','painPointsSolved','contentAngles','ctaIdeas'] as const).map(k=><label key={k} className={k==='ctaIdeas'?'md:col-span-2':''}><span className='text-sm'>{k}</span><textarea className='w-full rounded-xl border p-2 mt-1 min-h-24' value={p[k].join('\n')} onChange={e=>upd(k,e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))} /><span className='text-xs text-slate-500'>One item per line.</span></label>)}<div className='md:col-span-2 flex gap-2'><Button disabled={saving} onClick={async()=>{setSaving(true);setError('');const r=await fetch('/api/business/save-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:p})});const j=await r.json();setSaving(false);if(!r.ok){setError(j.error||'Save failed');return;}setSavedId(j.profile.id);setOk('Business profile saved.');}}> {saving?'Saving...':'Save Business Profile'} </Button><Button className='bg-emerald-600 hover:bg-emerald-700' disabled={gen} onClick={async()=>{setGen(true);setError('');const r=await fetch('/api/business/generate-promo-pack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:p,businessProfileId:savedId??undefined})});const j=await r.json();setGen(false);if(!r.ok){setError(j.error||'Generate failed');return;}setPromoPack(j.promoPack);setOk('Promo pack generated.');}}> {gen?'Generating promo pack...':'Generate Promo Pack'} </Button></div>{!savedId?<p className='md:col-span-2 text-xs text-slate-500'>Save this profile to keep future promo packs connected to this business.</p>:null}</section>:null}
{error?<div className='rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700'>{error}</div>:null}{ok?<p className='text-sm text-emerald-700'>{ok}</p>:null}
{promoPack?<PromoPackDisplay pack={promoPack} />:null}
</div>}
