"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";

type Profile = any;
export default function BusinessPage(){const [websiteUrl,setWebsiteUrl]=useState("");const [profile,setProfile]=useState<Profile|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [promoPack,setPromoPack]=useState<any>(null);const [savedId,setSavedId]=useState<string|undefined>();
const copy=async(v:string)=>navigator.clipboard.writeText(v);
async function analyze(){setLoading(true);setError("");try{const r=await fetch('/api/business/analyze-website',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({websiteUrl})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Analyze failed');setProfile(j.profile);}catch(e:any){setError(e.message);}finally{setLoading(false);}}
async function save(){const r=await fetch('/api/business/save-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile})});const j=await r.json();if(r.ok) setSavedId(j.profile.id);}
async function generate(){setLoading(true);setError("");try{const r=await fetch('/api/business/generate-promo-pack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,businessProfileId:savedId})});const j=await r.json();if(!r.ok) throw new Error(j.error||'Failed');setPromoPack(j.promoPack);}catch(e:any){setError(e.message);}finally{setLoading(false);}}
return <div className='mx-auto max-w-5xl space-y-6'><div><h1 className='text-3xl font-semibold'>Turn your website into promo content.</h1><p className='text-slate-600 mt-2'>Paste your website. ClipLoop learns your business and generates ready to post short form promo content.</p></div><div className='cl-card p-4 space-y-3'><input className='w-full rounded-xl border p-3' placeholder='https://yourbusiness.com' value={websiteUrl} onChange={e=>setWebsiteUrl(e.target.value)} /><Button onClick={analyze} disabled={loading}>{loading?'Analyzing...':'Analyze Website'}</Button>{error&&<p className='text-rose-600 text-sm'>{error}</p>}</div>{profile&&<div className='cl-card p-4 space-y-3'>{Object.entries(profile).map(([k,v])=><div key={k}><label className='text-sm font-medium'>{k}</label>{Array.isArray(v)?<textarea className='w-full border rounded p-2' value={v.join('\n')} onChange={e=>setProfile({...profile,[k]:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/>:<input className='w-full border rounded p-2' value={String(v??'')} onChange={e=>setProfile({...profile,[k]:e.target.value})}/>}</div>)}<div className='flex gap-2'><Button onClick={save}>Save Profile</Button><Button className='bg-slate-200 text-slate-900 hover:bg-slate-300' onClick={generate}>Generate Promo Pack</Button></div></div>}{promoPack&&<div className='cl-card p-4 space-y-4'><h2 className='text-xl font-semibold'>Latest Promo Pack</h2><pre className='text-xs whitespace-pre-wrap'>{JSON.stringify(promoPack,null,2)}</pre><Button onClick={()=>copy(JSON.stringify(promoPack,null,2))}>Copy Promo Pack</Button></div>}</div>}
