"use client";
import Link from "next/link";import { useEffect,useState } from "react";import { Button } from "@/components/ui/button";

type P={id:string;businessName:string|null;oneLineSummary:string|null;websiteUrl:string;industry:string|null;targetAudience:string|null;createdAt:string;updatedAt:string};
export default function Page(){const [profiles,setProfiles]=useState<P[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
async function load(){setLoading(true);setError("");try{const r=await fetch('/api/business/profiles');const j=await r.json();if(!r.ok)throw new Error(j.error||'Failed to load');setProfiles(j.profiles);}catch(e:any){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
async function del(id:string){if(!confirm('Delete this business profile and all promo packs?'))return;await fetch(`/api/business/profiles/${id}`,{method:'DELETE'});load();}
return <div className='space-y-5'><div><h1 className='text-3xl font-semibold'>Saved Business Profiles</h1><p className='text-slate-600 mt-1'>Businesses ClipLane has learned. Open any profile to generate new promo content from its saved context.</p><Link href='/dashboard/business' className='text-sm text-emerald-700'>+ Analyze a new website</Link></div>{loading?<div className='cl-card p-8 text-sm text-slate-500'>Loading profiles...</div>:error?<div className='rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-700 text-sm'>{error}</div>:profiles.length===0?<div className='cl-card p-8 text-sm text-slate-500'>No saved profiles yet.</div>:<div className='grid gap-4 md:grid-cols-2'>{profiles.map((p)=><div key={p.id} className='cl-card p-5 space-y-2'><h3 className='text-lg font-semibold'>{p.businessName||'Untitled business'}</h3><p className='text-sm text-slate-600'>{p.oneLineSummary||'No summary available.'}</p><p className='text-xs text-slate-500'>{p.websiteUrl}</p><p className='text-sm'><b>Industry:</b> {p.industry||'—'}</p><p className='text-sm'><b>Target audience:</b> {p.targetAudience||'—'}</p><p className='text-xs text-slate-500'>Created {new Date(p.createdAt).toLocaleString()} · Updated {new Date(p.updatedAt).toLocaleString()}</p><div className='flex gap-2 pt-1'><Link href={`/dashboard/business/${p.id}`}><Button>Open profile</Button></Link><Link href={`/dashboard/business/${p.id}`}><Button className='bg-emerald-600 hover:bg-emerald-700'>Generate promo pack</Button></Link><Button className='bg-rose-600 hover:bg-rose-700' onClick={()=>del(p.id)}>Delete</Button></div></div>)}</div>}</div>}
