"use client";
import Link from "next/link";import { useParams, useRouter } from "next/navigation";import { useEffect, useState } from "react";import { Button } from "@/components/ui/button";import type { BusinessProfile } from "@/lib/business/schemas";

type Pack={id:string;campaignTitle:string|null;positioningAngle:string|null;createdAt:string};
export default function Page(){const {id}=useParams<{id:string}>();const router=useRouter();const [profile,setProfile]=useState<BusinessProfile|null>(null);const [packs,setPacks]=useState<Pack[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [generating,setGenerating]=useState(false);const [msg,setMsg]=useState('');const [err,setErr]=useState('');
useEffect(()=>{if(!id)return;const load=async()=>{setLoading(true);setErr('');try{const r=await fetch(`/api/business/profiles/${id}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'Failed');setProfile(j.profile);setPacks(j.packs);}catch(e:any){setErr(e.message)}finally{setLoading(false)}};load();},[id]);
const setArr=(k:keyof BusinessProfile,v:string)=>setProfile((p)=>p?{...p,[k]:v.split('\n').map(x=>x.trim()).filter(Boolean)}:p);
if(loading)return <div className='cl-card p-8 text-sm text-slate-500'>Loading profile...</div>; if(err) return <div className='rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700'>{err}</div>; if(!profile)return null;
return <div className='space-y-5'><div className='flex justify-between gap-3 items-start'><div><h1 className='text-3xl font-semibold'>{profile.businessName||'Business profile'}</h1><p className='text-slate-600'>{profile.websiteUrl}</p></div><Link href='/dashboard/business/profiles' className='text-sm text-emerald-700'>Back to saved profiles</Link></div>
<div className='cl-card p-5 grid gap-3 md:grid-cols-2'>{['businessName','websiteUrl','industry','targetAudience','mainOffer','brandTone','oneLineSummary','longSummary'].map((k)=><label key={k} className={k==='oneLineSummary'||k==='longSummary'?'md:col-span-2':''}><span className='text-sm font-medium'>{k}</span><textarea className='mt-1 min-h-10 w-full rounded-xl border p-2 text-sm' value={(profile as any)[k]??''} onChange={e=>setProfile({...profile,[k]:e.target.value})} /></label>)}
<label><span className='text-sm font-medium'>productsOrServices</span><textarea className='mt-1 min-h-20 w-full rounded-xl border p-2 text-sm' value={profile.productsOrServices.join('\n')} onChange={e=>setArr('productsOrServices',e.target.value)} /></label>
<label><span className='text-sm font-medium'>keyBenefits</span><textarea className='mt-1 min-h-20 w-full rounded-xl border p-2 text-sm' value={profile.keyBenefits.join('\n')} onChange={e=>setArr('keyBenefits',e.target.value)} /></label>
<label><span className='text-sm font-medium'>painPointsSolved</span><textarea className='mt-1 min-h-20 w-full rounded-xl border p-2 text-sm' value={profile.painPointsSolved.join('\n')} onChange={e=>setArr('painPointsSolved',e.target.value)} /></label>
<label><span className='text-sm font-medium'>contentAngles</span><textarea className='mt-1 min-h-20 w-full rounded-xl border p-2 text-sm' value={profile.contentAngles.join('\n')} onChange={e=>setArr('contentAngles',e.target.value)} /></label>
<label className='md:col-span-2'><span className='text-sm font-medium'>ctaIdeas</span><textarea className='mt-1 min-h-20 w-full rounded-xl border p-2 text-sm' value={profile.ctaIdeas.join('\n')} onChange={e=>setArr('ctaIdeas',e.target.value)} /></label>
<div className='md:col-span-2 flex gap-2'><Button disabled={saving} onClick={async()=>{setSaving(true);setMsg('');setErr('');const r=await fetch(`/api/business/profiles/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile})});const j=await r.json();setSaving(false);if(!r.ok){setErr(j.error||'Failed');return;}setMsg('Profile updated.')}}>{saving?'Saving...':'Save changes'}</Button><Button className='bg-emerald-600 hover:bg-emerald-700' disabled={generating} onClick={async()=>{setGenerating(true);setErr('');setMsg('');const r=await fetch(`/api/business/profiles/${id}/packs`,{method:'POST'});const j=await r.json();setGenerating(false);if(!r.ok){setErr(j.error||'Failed');return;}setMsg('Promo pack generated.');window.location.reload();}}> {generating?'Generating...':'Generate New Promo Pack'} </Button><Button className='bg-rose-600 hover:bg-rose-700' onClick={async()=>{if(!confirm('Delete this profile and all promo packs?'))return;await fetch(`/api/business/profiles/${id}`,{method:'DELETE'});router.push('/dashboard/business/profiles')}}>Delete Profile</Button></div>
{msg?<p className='md:col-span-2 text-sm text-emerald-700'>{msg}</p>:null}{err?<p className='md:col-span-2 text-sm text-rose-700'>{err}</p>:null}</div>
<div className='cl-card p-5'><h2 className='text-xl font-semibold'>Promo Pack History</h2><div className='mt-3 space-y-3'>{packs.length===0?<p className='text-sm text-slate-500'>No promo packs yet.</p>:packs.map((p)=><div key={p.id} className='rounded-xl border p-4 flex flex-wrap justify-between gap-2 items-center'><div><p className='font-semibold'>{p.campaignTitle||'Untitled campaign'}</p><p className='text-sm text-slate-600'>{p.positioningAngle||'—'}</p><p className='text-xs text-slate-500'>{new Date(p.createdAt).toLocaleString()}</p></div><div className='flex gap-2'><Link href={`/dashboard/business/${id}/packs/${p.id}`}><Button>Open</Button></Link><Button className='bg-rose-600 hover:bg-rose-700' onClick={async()=>{if(!confirm('Delete this promo pack?'))return;await fetch(`/api/business/profiles/${id}/packs/${p.id}`,{method:'DELETE'});window.location.reload();}}>Delete</Button></div></div>)}</div></div></div>}
